services:
  similarPostsEngine:
    image: inamit323colman/collectiveiq-similar-posts-engine:latest
    container_name: collectiveiq-similar-posts-engine
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=${MONGO_USER}
      - DB_PASSWORD=${MONGO_PASSWORD}
      - DB_HOST=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - MODEL_NAME=all-MiniLM-L6-v2
      - MODEL_EMBEDDING_DIM=384
    networks:
      - my-network
  backend:
    image: inamit323colman/collectiveiq-backend:latest
    container_name: collectiveiq-backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${DB_URL}:${DB_PORT}/${DB_NAME}
      - ACCESS_TOKEN_EXPIRATION=1d
      - REFRESH_TOKEN_EXPIRATION=2d
      - TOKEN_SECRET=${TOKEN_SECRET}
      - FILE_SIZE_LIMIT=5242880
      - BASE_URL=https://collectiveiq.cs.colman.ac.il:3000/
      - SSL_PASSPHRASE=${SSL_PASSPHRASE}
      - TAG_STRING="try to attempt the best tag to the follow string from the existed ones, answer with one word only and only from the tags that you got from us!"
      - TAG_LIST="JavaScript, Python, Java, C#, Cooking, Health, Fitness, Travel, Photography, Food, Finance, Business, Politics, Gaming, Art, Literature, Music, Sports, Education, Parenting, Relationships, Mental-Health, Science, Psychology, Philosophy, Economics, Design, Self-Improvement, Entertainment, DIY, Gardening, Pets, History, Education, Astrology, Marketing, Books, Writing, Programming, Web-Development, Fashion, Beauty, Travel-Tips, Food-Recipes, Architecture, Language, Cooking-Tips, Makeup, Nutrition, Sleep, Technology, Meditation, Cryptocurrency, Environment, Sustainability, Yoga, Mindfulness, Law, Photography-Tips, Holidays, Crafts, Social-Media, Startups, Investments, Real-Estate, Engineering, Home-Improvement, Product-Design, Leadership, Career-Advice, Teaching, Relationships-Advice, Comedy, Movies, Nature, Hiking, Volunteering, Self-Care, Happiness, Music-Production, Graphic-Design, Web-Design, Acting, Productivity, Life-Hacks, Public-Speaking, Writing-Tips, Fashion-Design, Animal-Welfare, Charity, Mindfulness-Meditation, Mental-Wellbeing, Spirituality, Conflict-Resolution, Sociology, Childhood-Education, Language-Learning, Travel-Photography, Personal-Finance, Sustainable-Living"
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_USERID=684754652edbac2fbd17d541
      - LLAMA_USERID=684755392edbac2fbd17f25f
      - META_USERID=684755532edbac2fbd17f280
      - SIMILAR_POSTS_URL=http://10.10.248.152:8000
      - SIMILAR_POSTS_TOP_K=5
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - my-network

  frontend:
    image: inamit323colman/collectiveiq-frontend:latest
    container_name: collectiveiq-frontend
    environment:
      - NODE_ENV=production
    ports:
      - 443:443

networks:
  my-network:
    driver: bridge
