services:
  backend:
    image: inamit323colman/collectiveiq-backend:latest
    container_name: collectiveiq-backend
    ports:
      - 4000:3000
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${DB_URL}:${DB_PORT}/${DB_NAME}
      - ACCESS_TOKEN_EXPIRATION='1d'
      - REFRESH_TOKEN_EXPIRATION='2d'
      - TOKEN_SECRET=${TOKEN_SECRET}
      - FILE_SIZE_LIMIT=5242880
      - BASE_URL=https://node13.cs.colman.ac.il:4000/
      - SSL_PASSPHRASE=${SSL_PASSPHRASE}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - my-network

  frontend:
    image: inamit323colman/collectiveiq-frontend:latest
    container_name: collectiveiq-frontend
    environment:
      - NODE_ENV=production
    ports:
      - 443:443

networks:
  my-network:
    driver: bridge
